### ISSUE TITLE
Melon Nether world border issue

### ISSUE THREAD

**Issue by yungwilder** [theseedmc/issues#75]
**Describe the bug**
Melon Nether border is extremely small. This causes any portals near the edge to insta-kill the player when they arrive in the overworld as it thinks they are outside the border, but they are only around -2000, -2000

**To Reproduce**
1. Go to Melon
2. Tppos to -250, -250 (near the portal inquestion) or 250, 250 to see the edges of the border
3. Checked mushroom to confirm, I have homes in the nether that are in the thousands so something is off in melon. 

**Expected behavior**
Nether world border to be similar to the other servers

**Notes:**
This was seen 7/28 prior to the server issues

**Comment by gp-Airee** [comment]
Resolved with latest SeedNetherFix update.

**Comment by yungwilder** [comment]
@gp-Airee this is apparently not fixed on SeedNetherFix according to tech.
